name: Playwright Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repo
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2. Instalar Node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # 3. Instalar dependencias
      - name: Install dependencies
        run: npm ci

      # 4. Instalar browsers de Playwright
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # 5. Configurar variables de entorno
      - name: Set environment
        run: |
          echo "API_URL=https://api.qase.io/v1/" >> $GITHUB_ENV
          echo "UI_URL=https://app.qase.io" >> $GITHUB_ENV
          echo "TOKEN=${{ secrets.QASE_API_TOKEN }}" >> $GITHUB_ENV
          echo "EMAIL=${{ secrets.QASE_EMAIL }}" >> $GITHUB_ENV
          echo "PASSWORD=${{ secrets.QASE_PASSWORD }}" >> $GITHUB_ENV

      # 6. Ejecutar todos los tests
      - name: Run Playwright tests
        run: npx playwright test --reporter=dot,html

      # 7. Subir reportes como artifact
      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 7